use_frameworks!

target 'HaiLayoutPod_Example' do
  pod 'HaiLayoutPod', :path => '../'

  target 'HaiLayoutPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
